[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
#externref = "0.1.0"
wasm-bindgen = "0.2.0"
tiny-rng = "0.2.0"
harfbuzz-wasm = { path="../../../rust/harfbuzz-wasm"}
