#!/bin/sh

cp /mingw64/bin/libwinpthread-1.dll .
cp /mingw64/bin/libgcc_s_seh-1.dll .
cp /mingw64/bin/libstdc++-6.dll .
cp /mingw64/bin/avcodec-58.dll .
cp /mingw64/bin/libaom.dll .
cp /mingw64/bin/libcelt0-2.dll .
cp /mingw64/bin/libdav1d.dll .
cp /mingw64/bin/libgsm.dll .
cp /mingw64/bin/libiconv-2.dll .
cp /mingw64/bin/liblzma-5.dll .
cp /mingw64/bin/libmfx-1.dll .
cp /mingw64/bin/libmp3lame-0.dll .
cp /mingw64/bin/libopencore-amrnb-0.dll .
cp /mingw64/bin/libopencore-amrwb-0.dll .
cp /mingw64/bin/libopenjp2-7.dll .
cp /mingw64/bin/libopus-0.dll .
cp /mingw64/bin/libssp-0.dll .
cp /mingw64/bin/libspeex-1.dll .
cp /mingw64/bin/libtheoradec-1.dll .
cp /mingw64/bin/libtheoraenc-1.dll .
cp /mingw64/bin/libogg-0.dll .
cp /mingw64/bin/libvorbis-0.dll .
cp /mingw64/bin/libvorbisenc-2.dll .
cp /mingw64/bin/libvpx-1.dll .
cp /mingw64/bin/libwebp-7.dll .
cp /mingw64/bin/libwebpmux-3.dll .
cp /mingw64/bin/libx264-161.dll .
cp /mingw64/bin/libx265.dll .
cp /mingw64/bin/zlib1.dll .
cp /mingw64/bin/xvidcore.dll .
cp /mingw64/bin/avutil-56.dll .
cp /mingw64/bin/libvulkan-1.dll .
cp /mingw64/bin/swresample-3.dll .
cp /mingw64/bin/libsoxr.dll .
cp /mingw64/bin/libgomp-1.dll .
cp /mingw64/bin/avdevice-58.dll .
cp /mingw64/bin/libcaca-0.dll .
cp /mingw64/bin/libopenal-1.dll .
cp /mingw64/bin/SDL2.dll .
cp /mingw64/bin/libxml2-2.dll .
cp /mingw64/bin/avfilter-7.dll .
cp /mingw64/bin/libass-9.dll .
cp /mingw64/bin/libfontconfig-1.dll .
cp /mingw64/bin/libexpat-1.dll .
cp /mingw64/bin/libfreetype-6.dll .
cp /mingw64/bin/libbz2-1.dll .
cp /mingw64/bin/libbrotlidec.dll .
cp /mingw64/bin/libbrotlicommon.dll .
cp /mingw64/bin/libharfbuzz-0.dll .
cp /mingw64/bin/libglib-2.0-0.dll .
cp /mingw64/bin/libintl-8.dll .
cp /mingw64/bin/libpcre-1.dll .
cp /mingw64/bin/libgraphite2.dll .
cp /mingw64/bin/libpng16-16.dll .
cp /mingw64/bin/libfribidi-0.dll .
cp /mingw64/bin/avformat-58.dll .
cp /mingw64/bin/libbluray-2.dll .
cp /mingw64/bin/libgnutls-30.dll .
cp /mingw64/bin/libgmp-10.dll .
cp /mingw64/bin/libhogweed-6.dll .
cp /mingw64/bin/libnettle-8.dll .
cp /mingw64/bin/libidn2-0.dll .
cp /mingw64/bin/libunistring-2.dll .
cp /mingw64/bin/libp11-kit-0.dll .
cp /mingw64/bin/libffi-7.dll .
cp /mingw64/bin/libtasn1-6.dll .
cp /mingw64/bin/libmodplug-1.dll .
cp /mingw64/bin/librtmp-1.dll .
cp /mingw64/bin/libsrt.dll .
cp /mingw64/bin/libcrypto-1_1-x64.dll .
cp /mingw64/bin/postproc-55.dll .
cp /mingw64/bin/swscale-5.dll .
cp /mingw64/bin/libcurl-4.dll .
cp /mingw64/bin/libnghttp2-14.dll .
cp /mingw64/bin/libpsl-5.dll .
cp /mingw64/bin/libssh2-1.dll .
cp /mingw64/bin/libssl-1_1-x64.dll .
cp /mingw64/bin/libzstd.dll .
cp /mingw64/bin/libfreeimage-3.dll .
cp /mingw64/bin/libHalf-2_5.dll .
cp /mingw64/bin/libIex-2_5.dll .
cp /mingw64/bin/libIlmImf-2_5.dll .
cp /mingw64/bin/libIlmThread-2_5.dll .
cp /mingw64/bin/libImath-2_5.dll .
cp /mingw64/bin/libjpeg-8.dll .
cp /mingw64/bin/libjxrglue.dll .
cp /mingw64/bin/libjpegxr.dll .
cp /mingw64/bin/libraw-20.dll .
cp /mingw64/bin/libjasper-4.dll .
cp /mingw64/bin/liblcms2-2.dll .
cp /mingw64/bin/libtiff-5.dll .
cp /mingw64/bin/libdeflate.dll .
cp /mingw64/bin/libjbig-0.dll .
cp /mingw64/bin/libLerc.dll .
cp /mingw64/bin/libPocoData.dll .
cp /mingw64/bin/libPocoFoundation.dll .
cp /mingw64/bin/libPocoDataSQLite.dll .
cp /mingw64/bin/libsqlite3-0.dll .
cp /mingw64/bin/libPocoJSON.dll .
cp /mingw64/bin/libPocoNet.dll .
cp /mingw64/bin/libPocoNetSSL.dll .
cp /mingw64/bin/libPocoCrypto.dll .
cp /mingw64/bin/libPocoUtil.dll .
cp /mingw64/bin/libPocoXML.dll .
cp /mingw64/bin/SDL2_image.dll .
