//this file was auto-generated by res2h

#pragma once

#include <string>
#include <map>

extern const size_t arrow_svg_size;
extern const unsigned char arrow_svg_data[];

extern const size_t busy_0_svg_size;
extern const unsigned char busy_0_svg_data[];

extern const size_t busy_1_svg_size;
extern const unsigned char busy_1_svg_data[];

extern const size_t busy_2_svg_size;
extern const unsigned char busy_2_svg_data[];

extern const size_t busy_3_svg_size;
extern const unsigned char busy_3_svg_data[];

extern const size_t button_png_size;
extern const unsigned char button_png_data[];

extern const size_t button_filled_png_size;
extern const unsigned char button_filled_png_data[];

extern const size_t checkbox_checked_svg_size;
extern const unsigned char checkbox_checked_svg_data[];

extern const size_t checkbox_unchecked_svg_size;
extern const unsigned char checkbox_unchecked_svg_data[];

extern const size_t fav_add_svg_size;
extern const unsigned char fav_add_svg_data[];

extern const size_t fav_remove_svg_size;
extern const unsigned char fav_remove_svg_data[];

extern const size_t frame_png_size;
extern const unsigned char frame_png_data[];

extern const size_t off_svg_size;
extern const unsigned char off_svg_data[];

extern const size_t on_svg_size;
extern const unsigned char on_svg_data[];

extern const size_t opensans_hebrew_condensed_light_ttf_size;
extern const unsigned char opensans_hebrew_condensed_light_ttf_data[];

extern const size_t opensans_hebrew_condensed_regular_ttf_size;
extern const unsigned char opensans_hebrew_condensed_regular_ttf_data[];

extern const size_t option_arrow_svg_size;
extern const unsigned char option_arrow_svg_data[];

extern const size_t scroll_gradient_png_size;
extern const unsigned char scroll_gradient_png_data[];

extern const size_t slider_knob_svg_size;
extern const unsigned char slider_knob_svg_data[];

extern const size_t splash_svg_size;
extern const unsigned char splash_svg_data[];

extern const size_t star_filled_svg_size;
extern const unsigned char star_filled_svg_data[];

extern const size_t star_unfilled_svg_size;
extern const unsigned char star_unfilled_svg_data[];

extern const size_t textinput_ninepatch_png_size;
extern const unsigned char textinput_ninepatch_png_data[];

extern const size_t textinput_ninepatch_active_png_size;
extern const unsigned char textinput_ninepatch_active_png_data[];

extern const size_t window_icon_256_png_size;
extern const unsigned char window_icon_256_png_data[];

extern const size_t help_button_a_svg_size;
extern const unsigned char help_button_a_svg_data[];

extern const size_t help_button_b_svg_size;
extern const unsigned char help_button_b_svg_data[];

extern const size_t help_button_l_svg_size;
extern const unsigned char help_button_l_svg_data[];

extern const size_t help_button_r_svg_size;
extern const unsigned char help_button_r_svg_data[];

extern const size_t help_button_select_svg_size;
extern const unsigned char help_button_select_svg_data[];

extern const size_t help_button_start_svg_size;
extern const unsigned char help_button_start_svg_data[];

extern const size_t help_button_x_svg_size;
extern const unsigned char help_button_x_svg_data[];

extern const size_t help_button_y_svg_size;
extern const unsigned char help_button_y_svg_data[];

extern const size_t help_dpad_all_svg_size;
extern const unsigned char help_dpad_all_svg_data[];

extern const size_t help_dpad_down_svg_size;
extern const unsigned char help_dpad_down_svg_data[];

extern const size_t help_dpad_left_svg_size;
extern const unsigned char help_dpad_left_svg_data[];

extern const size_t help_dpad_leftright_svg_size;
extern const unsigned char help_dpad_leftright_svg_data[];

extern const size_t help_dpad_right_svg_size;
extern const unsigned char help_dpad_right_svg_data[];

extern const size_t help_dpad_up_svg_size;
extern const unsigned char help_dpad_up_svg_data[];

extern const size_t help_dpad_updown_svg_size;
extern const unsigned char help_dpad_updown_svg_data[];

struct Res2hEntry {
    const std::string relativeFileName;
    const size_t size;
    const unsigned char * data;
};

extern const size_t res2hNrOfFiles;
extern const Res2hEntry res2hFiles[];

typedef const std::map<const std::string, const Res2hEntry> res2hMapType;
extern res2hMapType res2hMap;
