/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.30.1-0-g5adbf3765 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.30.1-0-g5adbf3765"
#endif
#define SDL_REVISION_NUMBER 0
